# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BaseWebviewApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseWebviewApp

  target 'BaseWebviewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseWebviewAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'YHPhotoBrowser','~> 1.1.1'

end
